name: Control Staging Environment

# You can trigger manually, on push, or on a schedule
on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Choose your stateee!!!'
        required: true
        default: 'start'

jobs:
  control-env:
    runs-on: ubuntu-latest
    env:
      # These should be set in your repo’s Settings → Secrets
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
      AWS_REGION:        ${{ secrets.AWS_REGION }}
      MONGODB_ATLAS_PUBLIC_KEY:  ${{ secrets.ATLAS_PUBLIC_KEY }}
      MONGODB_ATLAS_PRIVATE_KEY: ${{ secrets.ATLAS_PRIVATE_KEY }}
      MONGODB_ATLAS_PROJECT_ID:  ${{ secrets.ATLAS_PROJECT_ID }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Setup AtlasCLI
        uses: mongodb/atlas-github-action@v0.2.0
        
      - name: Use AtlasCLI
        shell: bash
        run: atlas --version
      
      - name: Verify tools
        run: |
          aws --version
          atlas --version
          python --version
      
      - name: Set aws region
        run: |
          aws configure set region ap-southeast-1
      
      - name: Run test_connection.py
        run: |
          python test_connection.py 
      
      - name: Configure Atlas CLI
        env:
          ATLAS_PUBLIC_KEY: ${{ secrets.MONGODB_ATLAS_PUBLIC_KEY }}
          ATLAS_PRIVATE_KEY: ${{ secrets.MONGODB_ATLAS_PRIVATE_KEY }}
        run: |
          atlas config init <<EOF
          $ATLAS_PUBLIC_KEY
          $ATLAS_PRIVATE_KEY
          EOF
          
      - name: Run unified.py
        run: | 
          python unified.py ${{ github.event.inputs.action }}

